name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: large_ubuntu_32
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp .env.example .env
      - run: npm ci --include=optional
      - run: npm install solidity-comments-linux-x64-gnu
      - name: "npm CI test"
        run: |
          # sometimes not created and is not tailed
          touch fhevm.log
          npm run fhevm:start &
          sleep 60
          npm run test:inband
          npm run fhevm:stop || true
